### ISSUE TITLE
Would it be possible to add a section for world info as well?

### ISSUE THREAD

**Issue by TheFairyMan** [ausboss/PygDiscordBot#18]
Wondering if apart from cards it would be possible to load JSON files with world info or Lore books so when they're mentioned it just adds their context, like it is in KooldAI, SillyTavern and such, since adding everything to the character would be too much.

**Comment by ausboss** [comment]
I do want to revisit and add some stuff like that. At this time I have been doing some other related AI projects and I will bring back the things I learned to this project.

**Comment by TheFairyMan** [comment]
Ah, nice, that would be cool.
Also two little extra addition I would ask if it's possible is to allow the bot to monitor multiple channels and one for being able to tell it to send a preemptive message in one of them.

**Comment by ausboss** [comment]
You can list multiple channels separated by commas in the .env file like 12353213,145632565,2466322554 and it should keep the chat logs and conversation history separate. I've played around with the preemptive message before but ended up removing it because I'm constantly restarting it and it got annoying. I could probably add it back

**Comment by TheFairyMan** [comment]
Oh, I did it wrong them, I added a space after the comma and that gave me errors, thanks for letting me know.

y preemptive message I meant something like, you pass a command through the condole itself and tell the bot to go say hi or do something in a channel, not a startup message, just so it calls attention of people.

**Comment by ausboss** [comment]
Oh I could probably add a slash command for that. I'll play around with that idea and see how it goes

**Comment by TheFairyMan** [comment]
Ah, thank you, also, I noticed a new issue, the character information doesn't gets passed fully every time as the chat history starts to pile up, so the character jsut loses itself.

Also, do you have a set parameter for Temperature and such or does it use the one set on the kobold server running?

**Comment by TheFairyMan** [comment]
Another thing I wonder, do you have something that trims the messages?
because I see on the console log that way more tokens were generated, but the message seems to cut out on the first full stop(.) and character never completes their response if it takes multiple lines to do so.

**Comment by ausboss** [comment]
I did throw together some crude slash commands that let you change those model parameters from within discord . try pressing "/" and see if they pop up. Otherwise I just recommend opening up the pygbot.py file and manually tweaking them in there. Sorry that's the best I got for now but I will improve that soon. 
I am also going to work on a better response parsing message that will use a more "dynamic" stop token system.  The bots dont just stop after writing their message so it can get a little tricky on finding a way to only get the relevant parts. 
I need to fully understand what world info does and then I would be happy to add it. I'm just not exactly sure how they even achieved that in Kobold. I need to talk to Henky.

**Comment by TheFairyMan** [comment]
Thank you, will try changing it.
As for the "/" commands, it gives me an error for both set and get commands, while I was trying to get or set the temperature, but same errors also happens for for any other parameters that I try setting or getting, thus I'm not sure if the parameter changes were applied correctly when changed in the pybot.py, could also be because of the message parsing and being cut that it seems different, sadly the console doesn't display the response nor if the temp parameters were changed when the request arrived..
Also, maybe trying to do something similar to what TavernAI or KoboldAI (In chat mode) does, where it only looks to see if the bot has started trying to impersonate the user, then it cuts it off there, thou I'm not sure how that is done, u would need to ask either in TavernAI discord or the Kobold discord.
Also, is the parsing code easy to find? I could check and give it a try.
Error for set:
```
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\cogs\pygbot.py", line 259, in koboldput
    await interaction.response.send_message(embed=embedder(f"Error: {e}"), delete_after=12)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\interactions.py", line 778, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'koboldput' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
```
Error for Get:
```
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\cogs\pygbot.py", line 250, in koboldget
    await interaction.response.send_message(embed=embedder(f"Error: {e}"), delete_after=12)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\interactions.py", line 778, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'koboldget' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
```
the /followup also gives an error:
```
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\interactions.py", line 638, in defer
    await adapter.create_interaction_response(
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In name: Username cannot contain "discord"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\TheFairyMan\OneDrive\Documentos\Bots-Discord\PygDiscordBot\venv\lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'followup' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In name: Username cannot contain "discord"
```
