### ISSUE TITLE
Errors related to imagecaption and cilent.py and a ton of other stuff.

### ISSUE THREAD

**Issue by SanikkuDesu** [ausboss/PygDiscordBot#26]
Upon running the bot via it's bat file the following errors appear:

```
there was an error with the endpoint
Failed to load extension imagecaption
ExtensionFailed: Extension 'cogs.imagecaption' raised an error: ModuleNotFoundError: No module named 'torch'
```

Furthermore, after running the bot starts and recieves a message i get the following error:

```
CharacterName:←[0m
[2023-07-28 03:25:31] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\messagehandler.py", line 59, in on_message
    response = await self.bot.get_cog("chatbot").chat_command(message, message.clean_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\discord\ext\commands\core.py", line 588, in __call__
    return await self.callback(self.cog, context, *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\pygbot.py", line 243, in chat_command
    response = await self.chatbot.generate_response(message, message_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\pygbot.py", line 197, in generate_response
    response_text = conversation(input_dict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\base.py", line 258, in __call__
    raise e
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 412, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 543, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 449, in _generate_helper
    raise e
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 436, in _generate_helper
    self._generate(
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 922, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\koboldai.py", line 179, in _call
    response.raise_for_status()
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://challenges-restricted-computational-delicious.trycloudflare.com/api/v1/generate
```

I deleted the venv multiple times and reinstalling it, as well as making a clean install by cloning the git the proper way, I also tried reinstalling by clearing the pip cache in the rare chance a file got corrupted and nothing worked. Absolutely clueless how I could fix this. Might be a issue outside of my end?

**Comment by SanikkuDesu** [comment]
Image caption is now working, but I am still getting the exact same error after a message is sent.

**Comment by ausboss** [comment]
The error you posted earlier was related to the endpoint. Are you sure that is working? Post the error you see now

**Comment by SanikkuDesu** [comment]
```
Sanikku:  [sanikku posts a picture of a penguin standing in the snow]
CharacterName:
[2023-07-28 23:13:21] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\messagehandler.py", line 52, in on_message
    response = await self.bot.get_cog("chatbot").chat_command(message, image_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\discord\ext\commands\core.py", line 588, in __call__
    return await self.callback(self.cog, context, *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\pygbot.py", line 243, in chat_command
    response = await self.chatbot.generate_response(message, message_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\cogs\pygbot.py", line 197, in generate_response
    response_text = conversation(input_dict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\base.py", line 258, in __call__
    raise e
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 451, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 582, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 488, in _generate_helper
    raise e
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 475, in _generate_helper
    self._generate(
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\base.py", line 961, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\langchain\llms\koboldai.py", line 179, in _call
    response.raise_for_status()
  File "C:\Users\admin\Documents\GitHub\PygDiscordBot\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://judy-casino-blocked-as.trycloudflare.com/api/v1/generate
```

As you can see the error is the exact same as last time, but this time the image reading library caption is working as it outputs a caption for the image I gave it before printing the error, which is something that did not work last time.  [(if needed this is the image used to test.)](https://cdn.discordapp.com/attachments/1134353565087957043/1134685158801416192/1a36b305-412d-405e-a38b-0947ce6709ba.png)

Also the bot interpreting ANY message for me creates the error, not just sending images.  Please let me know if there's anything else I could provide to fix this problem.

A problem that might be related to the issue is that during setup it asks to update pip (22.3 -> 23.2.1), despite me already having done that. Any clue why it might be doing that? (Yes I've ran the proper pip install --upgrade pip command). I tried logging the console by running the batch file via CMD prompt and using >>C:\log.txt to output the console, but it did not save which requirement asks to update pip, but it does it after 3 certain requirements.

**Comment by ausboss** [comment]
The issue still says it is related to your endpoint. Meaning koboldai I would assume. Is your model loaded? Look at the endpoint you set in your .env . That's going to be the issue.

**Comment by SanikkuDesu** [comment]
I believe the model Is loaded. I am using the collab as the endpoint ATM, and if I go to the link directly, I can use kobold AI to play with the currently loaded model just fine.  Is there a setting I need to change on the actual kobold cilent?

**Comment by ausboss** [comment]
i pushed a fix. it was my fault. sorry about that 😔🙏
