### ISSUE TITLE
discord.client: Ignoring exception in on_message

### ISSUE THREAD

**Issue by sosiska123331827255** [ausboss/PygDiscordBot#27]
`[2023-08-01 01:45:02] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\PygDiscordBot-main\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\PygDiscordBot-main\cogs\messagehandler.py", line 59, in on_message
    response = await self.bot.get_cog("chatbot").chat_command(message, message.clean_content)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\discord\ext\commands\core.py", line 588, in __call__
    return await self.callback(self.cog, context, *args, **kwargs)  # type: ignore
  File "D:\PygDiscordBot-main\cogs\pygbot.py", line 243, in chat_command
    response = await self.chatbot.generate_response(message, message_content)
  File "D:\PygDiscordBot-main\cogs\pygbot.py", line 197, in generate_response
    response_text = conversation(input_dict)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\base.py", line 258, in __call__
    raise e
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 451, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 582, in generate
    output = self._generate_helper(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 488, in _generate_helper
    raise e
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 475, in _generate_helper
    self._generate(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 961, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\koboldai.py", line 179, in _call
    response.raise_for_status()
  File "D:\PygDiscordBot-main\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: UNPROCESSABLE ENTITY for url: http://localhost:5000/api/v1/generate`

I have no idea how to deal with this.... Lol...? This happens every time I write something

**Comment by ausboss** [comment]
pushed a fix for this.

**Comment by sosiska123331827255** [comment]
`[2023-08-03 17:38:35] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\PygDiscordBot-main\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\PygDiscordBot-main\cogs\messagehandler.py", line 59, in on_message
    response = await self.bot.get_cog("chatbot").chat_command(message, message.clean_content)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\discord\ext\commands\core.py", line 588, in __call__
    return await self.callback(self.cog, context, *args, **kwargs)  # type: ignore
  File "D:\PygDiscordBot-main\cogs\pygbot.py", line 230, in chat_command
    response = await self.chatbot.generate_response(message, message_content)
  File "D:\PygDiscordBot-main\cogs\pygbot.py", line 184, in generate_response
    response_text = conversation(input_dict)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\base.py", line 258, in __call__
    raise e
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 451, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 582, in generate
    output = self._generate_helper(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 488, in _generate_helper
    raise e
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 475, in _generate_helper
    self._generate(
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\base.py", line 961, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "D:\PygDiscordBot-main\venv\lib\site-packages\langchain\llms\koboldai.py", line 179, in _call
    response.raise_for_status()
  File "D:\PygDiscordBot-main\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: UNPROCESSABLE ENTITY for url: http://localhost:5000/api/v1/generate`

I still have the same error...

**Comment by ausboss** [comment]
which one of these are you choosing? 
![image](https://github.com/ausboss/PygDiscordBot/assets/102309304/3b2546cd-9448-4f92-8af7-f39e891a399c)

**Comment by sosiska123331827255** [comment]
I am choosing 1: Kobold

**Comment by sosiska123331827255** [comment]
I understand that sometimes issues can take time to resolve, but is there anything I can try to resolve the problem? Or if there is any updates.

**Comment by MaximoLiner** [comment]
it's been also happening to me
