### ISSUE TITLE
Cannot send empty message

### ISSUE THREAD

**Issue by Harry989** [ausboss/PygDiscordBot#37]
I'm having some issues with trying to generate responses, more often than not I get an error like this. I first assumed it was due to my VRAM usage basically topping out. But switching to Pyg2.7B did not alleviate this issue in the slightest. Any idea how to solve this issue?

`> Finished chain.
[2023-09-11 19:53:28] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\harry\Desktop\PygDiscordBot-main\venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\harry\Desktop\PygDiscordBot-main\cogs\messagehandler.py", line 64, in on_message
    await message.channel.send(response)
  File "C:\Users\harry\Desktop\PygDiscordBot-main\venv\lib\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\harry\Desktop\PygDiscordBot-main\venv\lib\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message`

**Comment by ktfcaptain** [comment]
Ever have any luck??  I just started trying to mess with the bot side of this stuff and none of them will actually communicate once running.  I'm losing my mind.
